//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Type
    {
        public string Activity_Name { get; set; }
        public Nullable<bool> isUpdated { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Activity_Category { get; set; }
        public int Activity_ID { get; set; }
    }
}
