//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manager()
        {
            this.Chef = new HashSet<Chef>();
        }
    
        public int M_Record_Number { get; set; }
        public Nullable<int> GM_Record_Number { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string Manager_Name { get; set; }
        public Nullable<bool> isUpdated { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chef> Chef { get; set; }
        public virtual Department Department { get; set; }
        public virtual Users Users { get; set; }
    }
}
