//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Product_Activity_Date = new HashSet<Product_Activity_Date>();
        }
    
        public int Product_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Activity_Date> Product_Activity_Date { get; set; }
        public virtual Product_Type Product_Type { get; set; }
    }
}
