//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Activity_Date
    {
        public int Activity_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Record_Number { get; set; }
        public string Activity_Category { get; set; }
        public Nullable<int> Old_Owner_Number { get; set; }
        public string Confirmation_Status { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isUpdated { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
